"""empty message

Revision ID: 079fc58036ad
Revises: 
Create Date: 2023-10-10 12:58:17.723172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079fc58036ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'status')
    op.add_column('users', sa.Column('document_type', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('document', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'document')
    op.drop_column('users', 'document_type')
    op.add_column('purchases', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
