"""empty message

Revision ID: 6675408b0cec
Revises: 9cac146568a8
Create Date: 2023-10-17 14:58:45.676705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6675408b0cec'
down_revision: Union[str, None] = '9cac146568a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vouchers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=60), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('register_date', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'products', ['name'])
    op.add_column('providers', sa.Column('nit', sa.String(), nullable=False))
    op.drop_column('providers', 'email')
    op.drop_column('purchases', 'status')
    op.drop_column('recipe_detail', 'unit_measure')
    op.add_column('users', sa.Column('document_type', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('document', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'document')
    op.drop_column('users', 'document_type')
    op.add_column('recipe_detail', sa.Column('unit_measure', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('providers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('providers', 'nit')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'register_date')
    op.drop_table('vouchers')
    # ### end Alembic commands ###
